'use strict';
(()=>{
const fixture=window.EXPLORER_FIXTURE, packet=fixture.packet, $=id=>document.getElementById(id);
const info=[{id:'R1_FOREWING_BAND',name:'Forewing band',plain:'The stripe across the upper wings. Try changing its color while keeping the pattern in place.',color:'#e63e4d',opacity:100,css:'coral'},{id:'R2_HINDWING_BAR',name:'Hindwing bar',plain:'The stripe across the lower wings. Compare it with the upper stripe: does each pattern tell a different story?',color:'#f2c84b',opacity:100,css:'gold'},{id:'R3_MARGIN_SPOTS',name:'Margin spots',plain:'Small marks near the wing edges. The original demo did not support these spots, so they start as ghost outlines. Adding color is your artistic choice.',color:'#c6d8df',opacity:0,css:'ghost'}];
let selected=0, compare=false, masks=false, zoom=1, depth='discover', question=0;
let traits=info.map(r=>({color:r.color,opacity:r.opacity}));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const changes=()=>info.flatMap((r,i)=>{const a=[];if(traits[i].color!==r.color)a.push(`${r.name}: color ${r.color} → ${traits[i].color}`);if(traits[i].opacity!==r.opacity)a.push(`${r.name}: visibility ${r.opacity}% → ${traits[i].opacity}%`);return a});
function shape(t,baseline=false){const prefix=baseline?'base':'edit';return `<svg viewBox="0 0 800 560" role="group" aria-label="${baseline?'Original synthetic pattern':'Editable butterfly schematic'}"><defs><linearGradient id="${prefix}-wing" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#354851"/><stop offset=".45" stop-color="#192630"/><stop offset="1" stop-color="#080f18"/></linearGradient><pattern id="${prefix}-scale" width="6" height="6" patternUnits="userSpaceOnUse"><path d="M0 2L3 0L6 2" stroke="#b9cfd4" stroke-opacity=".07" fill="none"/></pattern></defs><g transform="translate(400 280) scale(${zoom}) translate(-400 -280)">${fixture.wings.map(d=>`<path d="${d}" fill="url(#${prefix}-wing)" stroke="#59727b" stroke-width="1.5"/>`).join('')}${info.map((r,i)=>{const attrs=`${baseline?'':`data-region="${i}" role="button" tabindex="0" aria-label="Select ${r.name}"`} class="${baseline?'':'selectable'} ${!baseline&&selected===i?'selected':''}"`;const color=masks?['#6ad8c5','#c0a4ff','#d4dfeb'][i]:t[i].color; if(i<2)return `<g ${attrs} fill="${color}" fill-opacity="${t[i].opacity/100}">${fixture.geometry[r.id].map(d=>`<path d="${d}"/>`).join('')}</g>`;return `<g ${attrs} fill="${color}" fill-opacity="${t[i].opacity/100}" stroke="#aab9ca" stroke-width="1.5" stroke-dasharray="3 3">${[[112,250],[133,300],[180,445],[688,250],[667,300],[620,445]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="10"/>`).join('')}</g>`}).join('')}<g pointer-events="none">${fixture.wings.map(d=>`<path d="${d}" fill="url(#${prefix}-scale)"/>`).join('')}<path d="M375 260Q220 155 76 166 M371 278Q235 247 105 277 M425 260Q580 155 724 166 M429 278Q565 247 695 277 M376 323Q272 397 179 463 M424 323Q528 397 621 463" stroke="#769aa0" stroke-opacity=".23" stroke-width="2" fill="none"/><ellipse cx="400" cy="295" rx="23" ry="115" fill="#18242b" stroke="#71918f" stroke-width="2"/><path d="M383 220H417 M379 244H421 M378 268H422 M378 292H422 M379 316H421 M381 340H419 M385 364H415" stroke="#617e7c" stroke-opacity=".5"/><circle cx="400" cy="165" r="28" fill="#1c2c31" stroke="#71918f" stroke-width="2"/><path d="M390 150 Q350 92 322 60 M410 150 Q450 92 478 60" fill="none" stroke="#88aaa5" stroke-width="3"/></g></g></svg>`}
function draw(){const modified=changes();$('variantLabel').textContent=modified.length?'Your variation':'Source pattern';$('stateLabel').textContent=modified.length?'Exploratory drawing · unscored':'Synthetic demonstration';$('canvases').innerHTML=(compare?`<figure class="specimen">${shape(info,true)}<figcaption>SOURCE FIXTURE</figcaption></figure>`:'')+`<figure class="specimen">${shape(traits)}${compare?'<figcaption>YOUR VARIATION</figcaption>':''}</figure>`;$('stage').classList.toggle('mask-mode',masks);$('difference').textContent=modified.length?`${modified.length} visual change${modified.length===1?'':'s'} · ${modified.join(' · ')}`:'Original mask geometry recovered from the v0.6 prototype. Lighting, texture, and veins are illustrative.';document.querySelectorAll('[data-region]').forEach(el=>{el.onclick=()=>choose(Number(el.dataset.region));el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(Number(el.dataset.region));}}});}
function choose(i){selected=i;renderInspector();draw();document.querySelectorAll('[data-select]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.select)===i)));}
function renderInspector(){const r=info[selected], p=packet.regions[selected];$('inspectorHeading').innerHTML=`<div class="mobile-regions">${info.map((r,i)=>`<button data-select="${i}" aria-pressed="${i===selected}">${r.name}</button>`).join('')}</div><span class="eyebrow">REGION 0${selected+1}</span><h2>${r.name}</h2><p>${r.plain}</p>`;$('color').value=traits[selected].color;$('colorValue').textContent=traits[selected].color.toUpperCase();$('visibility').value=traits[selected].opacity;$('visibilityValue').textContent=traits[selected].opacity+'%';$('evidence').innerHTML=`<span class="eyebrow">FOLLOW THE FEATURE</span><h3>${selected===2?'An open question':'Where this pattern comes from'}</h3><p>${selected===2?'The source marks this region as unsupported. You can visualize a possibility without treating it as a discovery.':'This shape comes from our archived synthetic demonstration. It shows how a visible feature can carry a traceable evidence record.'}</p><ol><li>Wing region → named trait</li><li>Named trait → ${selected===2?'unresolved constraint':'synthetic constraint'}</li><li>${selected===2?'Support is insufficient.':'Source ends at synthetic data, not a real genome.'}</li></ol><div class="research-only"><h3>Original source identifiers</h3>${p.provenance_path.map(x=>`<p><code>${escape(x.layer)}<br>${escape(x.id)}</code></p>`).join('')}<p>Original packet state: <code>${escape(p.truth_state)}</code>. This state applies only within the synthetic fixture. No model is run by these controls.</p><details><summary>Inspect original region record</summary><pre>${escape(JSON.stringify(p,null,2))}</pre></details></div><a href="program_sources/${fixture.source_file}">Open original v0.6 prototype ↗</a>`;document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.select)));}
$('regions').innerHTML=info.map((r,i)=>`<button class="region-button" data-select="${i}" aria-pressed="${i===0}"><i class="legend-dot ${r.css}"></i>${r.name}<small>${i===2?'Unsupported · ghosted':'Synthetic source region'}</small></button>`).join('');
$('color').oninput=e=>{traits[selected].color=e.target.value;$('colorValue').textContent=e.target.value.toUpperCase();draw()};$('visibility').oninput=e=>{traits[selected].opacity=Number(e.target.value);$('visibilityValue').textContent=e.target.value+'%';draw()};
$('compare').onclick=()=>{compare=!compare;$('compare').setAttribute('aria-pressed',compare);draw()};$('masks').onclick=()=>{masks=!masks;$('masks').setAttribute('aria-pressed',masks);draw()};$('zoom').onclick=()=>{zoom=zoom===1?1.25:zoom===1.25?.8:1;$('zoom').textContent=Math.round(zoom*100)+'%';draw()};
document.querySelectorAll('[data-depth]').forEach(b=>b.onclick=()=>{depth=b.dataset.depth;document.body.classList.toggle('research',depth==='research');document.querySelectorAll('[data-depth]').forEach(x=>x.setAttribute('aria-pressed',x===b))});
function reset(){traits=info.map(r=>({color:r.color,opacity:r.opacity}));choose(selected);$('saveStatus').textContent='Source pattern restored. Changes stay in this tab until you export.'}
$('reset').onclick=reset;
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const palettes={source:['#e63e4d','#f2c84b'],ember:['#ff8846','#ffe1a5'],glacier:['#7ddfff','#9ee8d0'],violet:['#be99ff','#f5a9db']};traits=info.map((r,i)=>({color:i<2?palettes[b.dataset.preset][i]:r.color,opacity:r.opacity}));choose(selected)});
const questions=['What changes when a pattern keeps its shape but changes color?','Hide the lower-wing bar. Which features still make this pattern recognizable?','Compare two colors. What evidence would show whether a real butterfly could have them?','Add the ghosted spots. How would you test whether this new pattern exists in nature?'];$('challengeNext').onclick=()=>{$('challenge').textContent=questions[++question%questions.length]};
$('export').onclick=()=>{const record={schema:'LIFE-CODE-visual-variation-v1',created_at:new Date().toISOString(),scientific_core:'v0.11',interface:'v0.12.0',scope:'EXPLORATORY_DRAWING_NOT_BIOLOGICAL_PREDICTION',source:{file:fixture.source_file,sha256:fixture.source_sha256,packet_id:packet.packet_id,archived_packet_sha256:packet.freeze.packet_sha256},regions:traits.map((t,i)=>({region_id:info[i].id,...t,geometry:'UNCHANGED_SOURCE_MASK'})),changes:changes(),model_executed:false,score:null,illustrative_layers:['wing shading','veins','scale texture','body styling'],view:{compare,masks,zoom,depth}};const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='LIFE-CODE-visual-variation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('saveStatus').textContent='Variation download requested: JSON with source hash and every visual change.'};
choose(0);
})();
