/* Presentation of source-derived recovery records; no scientific values originate here. */
function resolveObjectId(id){return (S.object_aliases||[]).find(a=>a.legacy_object_id===id)?.canonical_object_id||id;}
function sourceLink(aid){const a=artById[aid];return a?.notes?.startsWith('Download: sources/')?`<a href="${esc(a.notes.slice(10))}" download>${esc(a.name)}</a>`:esc(a?.name||aid);}
function provenancePath(aid,seen=new Set()){
 if(seen.has(aid))return '<li>Repeated source reference</li>';seen.add(aid);
 const a=artById[aid],parents=(S.artifact_links||[]).filter(l=>l.child_artifact_id===aid);
 return `<li>${sourceLink(aid)}<p class=muted>${esc(a?.source_status||'Unknown source state')}</p><code class=hash>${esc(a?.sha256||'Hash not yet recovered')}</code>${parents.length?`<ul>${parents.map(l=>`<li>${esc(l.relation)}</li>${provenancePath(l.parent_artifact_id,new Set(seen))}`).join('')}</ul>`:''}</li>`;
}
function occurrencePanel(id){
 const ids=new Set([id,...S.edges.filter(e=>e.source_object_id===id&&e.edge_type==='HAS_MEMBER').map(e=>e.target_object_id)]);
 const rows=S.occurrences.filter(r=>ids.has(r.object_id));
 if(!rows.length)return '<div class=card><h3>Where it was found</h3><p>No occurrence coordinates have been released for this object yet.</p></div>';
 return `<div class=card><h3>Where it was found · ${rows.length} recorded locations</h3><p>These are addresses in the original DNA records. Counting starts at zero; the end address is the first base after the piece.</p><div class=table-scroll><table><caption>Verified direct-orientation locations from the frozen calibration</caption><thead><tr><th scope=col>Piece</th><th scope=col>Organism</th><th scope=col>DNA record</th><th scope=col>Start</th><th scope=col>End (exclusive)</th><th scope=col>Length</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.object_id)}</td><td>${esc(r.taxon_id.replace('TAX-',''))}</td><td>${esc(r.record_name)}</td><td>${r.start_0based}</td><td>${r.end_0based_exclusive}</td><td>${r.end_0based_exclusive-r.start_0based}</td></tr>`).join('')}</tbody></table></div><p class=learnBlock>Each piece was checked at its recorded address against the original genome file. Matching DNA does not by itself establish a shared biological job.</p><details class=researchBlock><summary>Complete occurrence records, assembly metadata, and source IDs</summary><pre>${esc(JSON.stringify(rows,null,2))}</pre></details></div>`;
}
function evidenceRecovery(){
 const words=S.vocabulary||[],events=S.ingest_events||[],audit=S.migration_audit||[];
 $('content').innerHTML=`<div class=hero><div class=eyebrow>Recovered evidence · Core ${esc(S.source_database.database_meta.version)}</div><h2>The original DNA evidence is back in the Codebook.</h2><p class=answer>Explore every shared 16-letter sequence from the three-genome pilot, inspect exactly where the selected pieces occur, and follow the sources behind each correction.</p></div>
 <div class=grid><div class=metric><div class=n>${words.length}</div><div class=l>distinct shared 16-base sequences</div></div><div class=metric><div class=n>${S.occurrences.length}</div><div class=l>verified focused locations</div></div><div class=metric><div class=n>${audit.length}</div><div class=l>audited record changes and additions</div></div></div>
 <div class=card><h3>Start with one piece</h3><p>The selected core occurs in the bacterium, archaeon, and yeast. In the bacterium and archaeon it sits inside block B. The sequence record and its later biological interpretation remain separate.</p><div class=downloads><button class=action data-recovered-object="PC1-CORE-16">Explore the shared core</button><button class=action data-recovered-object="PC1-MODULE-RIBO">Inspect the DNA neighborhood</button></div><p class=muted>These focused locations describe three selected pieces; they are not a coordinate catalog for all ${words.length} vocabulary sequences.</p></div>
 <div class=card><h3>Search the complete shared vocabulary</h3><p>Each row is one exact sequence found in all three pilot genomes. Counts tell you how many times it occurs within each genome. Repeated letters are kept in the evidence.</p><label for=wordSearch>Find a DNA sequence or part of one</label><input id=wordSearch autocomplete=off spellcheck=false placeholder="Enter A, C, G, or T"><p id=wordCount role=status aria-live=polite></p><div class=table-scroll id=wordTable></div><p class=learnBlock>Entropy describes the variety of letters in a sequence. Low entropy means more repetition. It does not mean the sequence is useless or should be removed.</p><div class=downloads><a href="sources/TRIPLE_SHARED_16MERS_COMPLETE.csv" download>Original 54-sequence CSV</a></div></div>
 <div class=card><h3>A correction you can inspect</h3><p>The older continuation reversed the A/B labels. The original source names the 25-base piece A and the 24-base piece B. Core v0.10 restores those names and updates the related lengths, containment, and directional links.</p><div class=table-scroll><table><thead><tr><th>Earlier ID</th><th>Corrected ID</th></tr></thead><tbody>${(S.object_aliases||[]).map(a=>`<tr><td>${esc(a.legacy_object_id)}</td><td><button class=tab data-recovered-object="${esc(a.canonical_object_id)}">${esc(a.canonical_object_id)}</button></td></tr>`).join('')}</tbody></table></div><p>Earlier IDs still resolve to the corresponding piece. The original release remains available for comparison.</p></div>
 <div class=card><h3>Follow the recovery checks</h3>${events.map(e=>`<p>Recovery recorded ${esc(e.event_date)}. This is the ingestion date, not a reconstructed historical freeze date.</p><dl class=checks>${Object.entries(JSON.parse(e.validation_json)).map(([k,v])=>`<dt>${esc(k.replaceAll('_',' '))}</dt><dd>${esc(String(v))}</dd>`).join('')}</dl>`).join('')}<p>EXP-0002 outcomes remain sealed. Recovery of calibration evidence does not reveal the running experiment.</p></div>
 <div class=card><h3>Original source trail</h3><ul>${provenancePath('ART-PC0001-RAW')}</ul><div class=downloads><a href="sources/PC1_MAXIMAL_BLOCKS_GE24.csv" download>Independent block table</a><a href="data/LIFE_CODE_PUBLIC_CODEBOOK_v0.11.json" download>Complete current JSON</a><a href="downloads/LIFE_CODE_CODEBOOK_CORE_v0.11.sqlite" download>Current SQLite Codebook</a></div></div>
 <div class=card><h3>What changed in the records?</h3><p>Every changed or added scientific row has a before/after record. Nothing here adds a new experimental outcome.</p><label for=auditSearch>Find an object ID, measurement, or table</label><input id=auditSearch placeholder="Try PC1-M02, occurrences, or vocabulary"><div id=auditRows></div></div>`;
 const drawWords=()=>{const q=$('wordSearch').value.trim().toUpperCase();const rows=words.filter(w=>w.sequence.includes(q));$('wordCount').textContent=`${rows.length} of ${words.length} sequences`;$('wordTable').innerHTML=`<table><caption>Frozen direct-orientation recurrence; no reverse-complement pooling</caption><thead><tr><th>Exact 16-base sequence</th><th>E. coli</th><th>Pyrococcus</th><th>Yeast</th>${lens==='research'?'<th>Entropy (bits)</th><th>Record ID</th>':''}</tr></thead><tbody>${rows.map(w=>`<tr><td><code class=dna>${esc(w.sequence)}</code>${w.sequence===byId['PC1-CORE-16'].sequence?' <span class=badge>Selected core</span>':''}</td><td>${w.ecoli_occurrences}</td><td>${w.pyro_occurrences}</td><td>${w.yeast_occurrences}</td>${lens==='research'?`<td>${w.entropy_bits}</td><td><code>${esc(w.vocabulary_id)}</code></td>`:''}</tr>`).join('')}</tbody></table>`;};
 const drawAudit=()=>{const q=$('auditSearch').value.trim().toLowerCase();const rows=audit.filter(a=>(a.table_name+' '+a.record_id).toLowerCase().includes(q));$('auditRows').innerHTML=`<p role=status>${rows.length} matching audit records</p>`+rows.map(a=>`<details><summary>${esc(a.table_name)} · ${esc(a.record_id)}</summary><p>${esc(a.reason)}</p><h4>Before</h4><pre>${esc(a.before_json?JSON.stringify(JSON.parse(a.before_json),null,2):'Record did not exist')}</pre><h4>After</h4><pre>${esc(a.after_json?JSON.stringify(JSON.parse(a.after_json),null,2):'Superseded; see alias mapping')}</pre></details>`).join('');};
 $('wordSearch').oninput=drawWords;$('auditSearch').oninput=drawAudit;drawWords();drawAudit();document.querySelectorAll('[data-recovered-object]').forEach(b=>b.onclick=()=>selectObject(b.dataset.recoveredObject));
}
