/* Historical records are read from a database-derived snapshot. */
let researchQuery='',researchKind='',researchStatus='';
function historicalRecord(id){return (window.LIFE_CODE_RESEARCH?.research_records||[]).find(r=>r.record_id===id);}
function researchStatusLabel(status){return status.replaceAll('_',' ').toLowerCase();}
function historicalLink(id){const r=historicalRecord(id);return r?`<button class=tab data-research-id="${esc(id)}">${esc(id)}</button>`:`<span class=muted>${esc(id)} · not in this public release</span>`;}
function bindResearch(){document.querySelectorAll('[data-research-id]').forEach(b=>b.onclick=()=>showHistoricalRecord(b.dataset.researchId));}
function researchLedger(){
 const d=window.LIFE_CODE_RESEARCH,rs=d.research_records,preds=rs.filter(r=>r.kind==='prediction');
 const statuses=[...new Set(rs.map(r=>r.status))].sort();
 const totals=Object.entries(preds.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{})).sort(([a],[b])=>a.localeCompare(b));
 $('content').innerHTML=`<div class=hero><div class=eyebrow>The research record · Archive ${esc(d.metadata.archive_version)}</div><h2>Follow the questions. Inspect the results. Keep the failures.</h2><p class=answer>The research went beyond exact DNA matches. Here you can follow which ideas survived their tests, which weakened, and which remain untested.</p></div>
 <div class=grid><div class=metric><div class=n>${rs.filter(r=>r.kind==='entry').length}</div><div class=l>historical Codebook entries</div></div><div class=metric><div class=n>${preds.length}</div><div class=l>historical predictions</div></div><div class=metric><div class=n>${d.research_assertions.length}</div><div class=l>evidence statements with original classes</div></div></div>
 <div class=callout><b>Read these as historical records.</b> ${esc(d.metadata.historical_status_note)} ${d.metadata.held_record_count} archive records are held from this public release. A recorded success does not establish a universal biological language.</div>
 <details class=card open><summary><b>A guided path through the research</b></summary><div class=timeline>${d.research_reading_guide.map((g,i)=>`<article class=mile><div class=question>Question ${i+1}</div><h3>${esc(g.title)}</h3><p>${esc(g.plain_explanation)}</p><div class=downloads>${JSON.parse(g.record_ids_json).map(historicalLink).join('')}</div></article>`).join('')}</div></details>
 <div class=card><h3>Prediction outcomes, exactly as recorded</h3><p>These tests address different questions and use different controls. The counts below are an inventory, not a success rate or a pooled measure of scientific confidence.</p><div class=statusinventory>${totals.map(([state,n])=>`<button class=tab data-outcome="${esc(state)}">${esc(researchStatusLabel(state))} · ${n}</button>`).join('')}</div></div>
 <div class=card><h3>Search the complete published research record</h3><label for=researchSearch>Search statements, source names, IDs, or unknowns</label><input id=researchSearch placeholder="Try entropy, FALSIFIED, or LC-PRED-0049" value="${esc(researchQuery)}"><div class=split><label for=researchKind>Record kind<select id=researchKind><option value="">All records</option><option value=entry>Codebook entries</option><option value=prediction>Predictions</option></select></label><label for=researchStatus>Original status<select id=researchStatus><option value="">All statuses</option>${statuses.map(x=>`<option value="${esc(x)}">${esc(researchStatusLabel(x))}</option>`).join('')}</select></label></div><p id=researchCount role=status aria-live=polite></p><div id=researchResults></div></div>
 <div class=card><h3>The current scientific frontier</h3><p>The fresh-panel model-v3 predictions are frozen and untested in archive v0.0.81. Its training diagnostics are development evidence. Later EXP-0002 progress does not change these archived prediction outcomes.</p><div class=downloads>${['LC-ARCH-0015','LC-PRED-0049','LC-PRED-0050','LC-PRED-0051'].map(historicalLink).join('')}</div></div>
 <div class=downloads><a href="data/LIFE_CODE_RESEARCH_v0.11.json" download>Full research JSON</a><a href="downloads/LIFE_CODE_CODEBOOK_CORE_v0.11.sqlite" download>Complete Core v0.11 SQLite</a><a href="research/release_manifest_v0.11.json" download>Release coverage and source hashes</a></div>`;
 const draw=()=>{researchQuery=$('researchSearch').value;researchKind=$('researchKind').value;researchStatus=$('researchStatus').value;const q=researchQuery.toLowerCase();const matches=rs.filter(r=>(!researchKind||r.kind===researchKind)&&(!researchStatus||r.status===researchStatus)&&(!q||(r.record_id+' '+r.status+' '+r.original_json).toLowerCase().includes(q)));$('researchCount').textContent=`${matches.length} of ${rs.length} published records`;$('researchResults').innerHTML=matches.map(r=>{const p=JSON.parse(r.original_json);const statement=p.statement||p.evidence?.[0]?.statement||r.record_id;return `<article class=finding><div class=badges>${badge(r.kind)}${badge(researchStatusLabel(r.status),r.status.includes('FALSIFIED')?'bad':'')}</div><h3>${esc(r.record_id)}</h3><p>${esc(statement)}</p><button class=action data-research-id="${esc(r.record_id)}">Read evidence, limits, and sources →</button></article>`}).join('')||'<p>No records match. Clear a filter to broaden the search.</p>';bindResearch();};
 $('researchKind').value=researchKind;$('researchStatus').value=researchStatus;$('researchSearch').oninput=draw;$('researchKind').onchange=draw;$('researchStatus').onchange=draw;document.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=()=>{$('researchKind').value='prediction';$('researchStatus').value=b.dataset.outcome;$('researchSearch').value='';draw();$('researchSearch').focus();});draw();bindResearch();
}
function showHistoricalRecord(id){
 const d=window.LIFE_CODE_RESEARCH,r=historicalRecord(id);if(!r)return;view='researchRecord';current=id;setExplorer(false);updateLocation('#research='+encodeURIComponent(id));
 const p=JSON.parse(r.original_json),assertions=d.research_assertions.filter(a=>a.record_id===id),links=d.research_links.filter(l=>l.source_id===id),sources=d.research_record_sources.filter(x=>x.record_id===id).map(x=>d.research_sources.find(s=>s.source_name===x.source_name));
 const classes={E0:'The artifact reports',E1:'A calculation from the evidence',E2:'Biological identification added after freeze',I1:'An interpretation with limits',P1:'A prediction to test',H1:'A broader hypothesis',X:'Rejected or superseded'};
 const boundaries=Object.entries(p).filter(([k])=>/unknown|falsification|support_condition|weakening|boundary|gate|limitation|constraint/.test(k));
 $('content').innerHTML=`<button class=tab id=backResearch>← Research record</button><div class=hero><div class=eyebrow>${esc(r.kind)} · archive v${esc(r.archive_version)}</div><h2>${esc(id)}</h2><div class=badges>${badge(researchStatusLabel(r.status),r.status.includes('FALSIFIED')?'bad':'')}${badge(r.record_type)}</div><p>This is the original record at the archive cutoff. Historical observations, later interpretations, and open questions remain separate.</p></div>
 ${assertions.map(a=>`<article class=card><div class=question>${esc(classes[a.evidence_class]||a.evidence_class)} <span class=badge>${esc(a.evidence_class)}</span></div><p class=answer>${esc(a.statement)}</p></article>`).join('')}
 ${p.validation?`<div class=card><h3>Recorded test outcome</h3>${historicalFields(p.validation)}</div>`:''}
 ${p.observations?`<div class=card><h3>Recorded observations</h3>${historicalFields(p.observations)}</div>`:''}
 <div class=card><h3>Limits and open questions</h3>${boundaries.length?boundaries.map(([k,v])=>`<h4>${esc(k.replaceAll('_',' '))}</h4>${historicalFields(v)}`).join(''):'<p>No separate boundary field is stored in this record. Evidence statements retain their original qualifications.</p>'}<p class=muted>Similar sequence or broad context does not by itself establish mechanism, interchangeability, or a universal instruction set.</p></div>
 <div class=card><h3>Connected research</h3>${links.length?links.map(l=>`<p>${esc(l.relation)}: ${historicalLink(l.target_id)}</p>`).join(''):'<p>No explicit record links stored.</p>'}</div>
 <div class=card><h3>Source evidence</h3><p>Source hashes verify archive identity. They do not mean these experiments were rerun or independently replicated for this website.</p>${sources.map(s=>`<details><summary>${esc(s.source_name)} · ${esc(s.release_state.replaceAll('_',' ').toLowerCase())}</summary><p>${s.bytes} bytes</p><code class=hash>${esc(s.sha256)}</code>${s.release_state==='PUBLISHED'?`<p><a href="research/sources/${encodeURIComponent(s.source_name)}" download>Download original source</a></p>`:'<p>Source bytes are not distributed in this release. The original reference and hash remain recorded.</p>'}</details>`).join('')}</div>
 <details class=card ${lens==='research'?'open':''}><summary><b>Complete original record</b></summary><pre>${esc(JSON.stringify(p,null,2))}</pre><code class=hash>SHA-256 ${esc(r.source_sha256)}</code><p><a href="research/${esc(r.source_path)}" download>Download original JSON bytes</a></p></details>`;
 $('backResearch').onclick=()=>setView('research');bindResearch();$('content').focus({preventScroll:true});
}
function historicalFields(v){if(Array.isArray(v))return v.length?`<ul>${v.map(x=>`<li>${typeof x==='object'?historicalFields(x):esc(String(x))}</li>`).join('')}</ul>`:'<p class=muted>None recorded.</p>';if(v!==null&&typeof v==='object')return `<div class=table-scroll><table><tbody>${Object.entries(v).map(([k,x])=>`<tr><th scope=row>${esc(k.replaceAll('_',' '))}</th><td>${typeof x==='object'?historicalFields(x):esc(String(x))}</td></tr>`).join('')}</tbody></table></div>`;return `<p>${esc(String(v))}</p>`;}
